network: true

headers:
  Content-Security-Policy: "
    default-src 'self' *.toolforge.org *.wikimedia.org analytics.wikimedia.org;
    script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://unpkg.com https://cdn.jsdelivr.net *.toolforge.org;
    style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com;
    font-src 'self' data: https://cdnjs.cloudflare.com https://fonts.gstatic.com;
    connect-src 'self' *.toolforge.org analytics.wikimedia.org;
  "
